#:schema node_modules/wrangler/config-schema.json
name = "fp-data-api"
main = "src/index.ts"
compatibility_date = "2024-07-01"
node_compat = true

[placement]
mode = "smart"

# Bind a Hyperdrive configuration. Use to accelerate access to your existing databases from Cloudflare Workers.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#hyperdrive
[[hyperdrive]]
binding = "fitness-db"
id = "600b3751adb24a88aaa6ad555550054d"